export default {
  cognito: {
    REGION: "AWS_REGION",
    USER_POOL_ID: "AWS_USER_POOL_ID",
    APP_CLIENT_ID: "AWS_APP_CLIENT_ID",
    SECRET_ACCESS_KEY: "AWS_SECRET_ACCESS_KEY",
    POOL_ARN: "AWS_POOL_ARN",
    ACCESS_ID: "AWS_ACCESS_ID",
    DOMAIN_PREFIX: "AWS_DOMAIN_PREFIX"

  }
};